### ISSUE TITLE
Per project vs Per Organization Funding

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/project-funding#2]
In my opinion we should consider the advantages vs disadvantages of collecting donations per projects vs the entire organization. The choice shifts where the engineering decisions are made. One could argue these engineering decisions are best left within the development organization or engineering decisions would be best decided through a form of direct democracy. I can see the advantages and disadvantages of each system but I think we should think critically about this decision before moving forward because it has a lot of cascading affects.

**Comment by realcodywburns** [comment]
I am hoping to create a single point of donation for the community at large. Essentially creating one multi-wallet for everyone who wants to support the community but not really be to far in the weeds with the inner workings of  development.

In my vision; sub-organisations(both internal and external to the devgroup)  would form to create proposals for ETC related projects. If three coders in South Africa need funding to hire a UX designer, this would be where they could come for funding. If we need to pay for server space to host vms for development, the committee could fund it. 

It would allow coders to focus on coding rather than panhandling.

**Comment by ProphetDaniel** [comment]
I read this [Centralized Vs. Decentralized Organizational Structure](http://smallbusiness.chron.com/centralized-vs-decentralized-organizational-structure-2785.html).

In my opinion we need to develop a decentralized way of doing it as that is inline with our manifest. But to make this happen right it's going to take some time until we have a secure framework.

In the other hand we cannot afford to loose great developers in the meanwhile the framework is being developed. So my opinion right now is to stick with the centralized structure for the initial funding to make decisions faster.

**Comment by soundbit** [comment]
look crowdsourcing model http://quirky.com 
![image](https://cloud.githubusercontent.com/assets/20613272/17339672/938ed69e-58f5-11e6-99a8-cc99cb19e28a.png)

https://files.slack.com/files-pri/T1TAXQBGF-F1XAL9D09/pasted_image_at_2016_08_02_11_33_am.png

**Comment by NDNewell** [comment]
Agreed @ProphetDaniel - I think avoiding anything that resembles a 'foundation' or 'committee' that makes decisions on behalf of all ETC participants should be avoided at all costs. Per project crowdfunding is most likely the best way to go. While it may seem like panhandling by devs, it's important to remember that a great idea/project will sell itself.

**Comment by soundbit** [comment]
@NDNewell @ProphetDaniel I also agree with this, but it is important to eliminate fraud in the funding of internal projects

**Comment by NDNewell** [comment]
@soundbit could you pls describe a scenario where fraud might happen via crowdfunding internal projects?

**Comment by soundbit** [comment]
@NDNewell the developer received money and not done the work. Perhaps it performed poorly. Maybe the developers will receive funding of short pieces?

**Comment by ProphetDaniel** [comment]
As far as I understook [Quirky](quirky.com) looks a professional way for handling the community funding of projects. Personally speaking I loved it. Anyway I'll study a little bit more, and I invite you to do the same. The target is to have a better position really soon.

At the same time centralized donations to the adresses advertised in the [main page](www.ethereumclassic.org) and [wiki page](http://ethcwiki.org/index.php?title=Contribute) will occurr. So we have the opportunity to make a great balance between the two worlds.

**Comment by NDNewell** [comment]
I suggest we continue this discussion in the slack channel [https://ethereumclassic.slack.com/messages/community/](url) where avtarsehra has made some good suggestions.

**Comment by avtarsehra** [comment]
Hi All, frictionless funding is a fundamental part of any successful ecosystem. We've been working on getting the key foundations in place regarding a global community, which is coming along nicely, so we can leverage this to drive funding campaigns when the funding operations are deployed.  In terms of Fundraising operations themselves (tech, people and processes), they need to be thought through and deployed very carefully as suggested by many of you. At this stage there is no right or wrong answer, and it will be a steep learning curve to get right. But my suggestion will be to deploy operations that are agile and easy to iterate/pivot. This means if something is not working it can be changed. Eventually, once the system is perfected we can embed the final solution.

Obviously we wont be bale to collect funding in fiat currency unless we setup a legal entity. This is something we are looking into, as long as it can be done in an appropriate way that is aligned with the fundamental principles of this community.   

The quickest method will be to collect money in BTC/ETC (and dare I say ETH). But the only point of question is that should fundraising be on a project basis or at the organisation level. My view is that, either way, the allocation of funds will need to be done through a consensus of the community, so collecting money at one level or the other shouldn't be too much of big concern. However, this shouldn't mean that we couldn't have a ongoing fundraising campaign project that collects funds at the organisation level, which can then also allocate funds for core infrastructure work, some of which may not be easy to market to general crowdfunding. But then for DAPP developers, they should be given the flexibility to market their ideas and raise money on the same funding platform. However, as NDWell notes, we need to make sure there is a way to ensure transparency and accountability, e.g. fundraisers connect with their social accounts, and communicate progress to community regularly, and provide means to the community to rate fundraisers so the best developers, or those that make the best use of the funds, gain more exposure as time goes on.

Will be good to discuss further, and I can share more of the things we are doing related to coming up with a legal framework for something that could be more sustainable in the long term.

**Comment by whatisgravity** [comment]
I want to add, I think at this point we should focus on simplicity and security. We need to get something in production which: 

1. Holds donated funds in a transparent way.
2. Is controlled by multiple trusted members of the development in a way that is not easy to game. 
3. Has payout function built in a modular way so we can easily change out the way payouts from the trust work.

If we take the time to make the make the output function of the donations modular, we can change how funds are divided among projects later. This would satisfy immediate demands and allow us to adapt the system to community needs change in the future.

**Comment by realcodywburns** [comment]
So something similar to https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol then?  
This contract creates a multi that has a controllable daily withdrawal limit above which requires multisig and unlimited owners. Everyone involved can interact at a human level to decide who gets what. One address to point money to, anyone can pull money out.

**Comment by GillesChamp** [comment]
You have exactly the same problem of all the organizations in the world. Why do you want to reject the idea of a Foundation or  a consortium or any sort of no-profit organization ? There is not so much time and at any moment a small new group can take a prominent position. What if, suppose,  3 new developers should start to work on some new tools right now asking to be crowdfunded as Ethereum Classic Consortium? They would be able to  take  some sort of imprimatur  while you are wasting your time in long discussions. I suggest you involve in your group a consultant able to drive you in a consortium and once done you will put mind to how to use the collected funds.  In the mean time, add a web page to your site with the donor list and do not forget that the Ethereum Fundation has legal rights on the term "Etehreum" so  - probably - any official organization started to manage ETC must avoid the term "ETHEREUM" in the name, that is a real issue.

**Comment by realcodywburns** [comment]
@GillesChamp I think the current opposition is to perception of central management of the space which is generally against the groups intention. I see value in uniting and forming a group that can be a visible core of the 'new' coin. As I have suggested, some people just want to give money and don't want to get into the weeds of finding out which project is the deserving. I do not think this jeopardizes decentralization, openness, or general crypto-anarchy. see: free software foundation, electronic frontier foundation, creative commons, Linux foundation, apache, etc.  

Creating an ET Confederation, or whatever, would allow funding of large projects by gathering large capital. Most importantly, as you have pointed out, an organisation can hold intellectual property for a community. Currently there is nothing, except morals,  stopping the Ethereum foundation form crashing in and reclaiming/controlling both chains. A club could public domain essential code or images. It could join with the above mentioned groups and fight for, in the legal sense, the freedom of the platform.       

I think a sound argument could be made that the Ethereum Foundation took deliberate steps and essentially genericized their trade mark. But an IP lawyer would be a better judge of that. 

_cue overly dramatic closing_

Unite or die! The sooner the better; else ethereum<sup>classic</sup> will go gentle into that good night .

**Comment by realcodywburns** [comment]
We are not deciding against being a starfish or a spider. We are deciding on a meta level if 'we' exist..

**Comment by GillesChamp** [comment]
@realcodywburns "Currently there is nothing, except morals, stopping the Ethereum foundation form crashing in and reclaiming/controlling both chains" - That is the reason I'm here, now,  together hundreds of other people around the world - I think the "moral" is a very great asset and what I love to think is that you can capitalize this asset quickly,

**Comment by ProphetDaniel** [comment]
Im my understanding as I have stated in my last coment [here](https://github.com/ethereumclassic/README/issues/33) we are part of a Civic & Social Organization that aims improving society for a better place to live. As @GillesChamp pointed out, the [organization values](http://elvalordelosvalores.com/los-valores-organizacionales/) are the most important asset an organization can have.

> The good or bad working of an organization is detemined by the solidity of its values.
- Juan Carlos Jímenez

Ethereum<sup>CLASSIC</sup> won't improve society for a better place to live if it fails.
If resources are not properly invested, projects eventually fail, I have to highlight that.

We are called by the community to take a decision here though. This decision can't be irreversible (@avtarsehra) or too costly to revert. In my understanding we should use a third party solution like the one suggested by @soundbit above [Quirky](http://quirky.com). If it doesn't work for us, we switch to another one if available, or if there isn't any, we can only then develop custom solution with the experience acquired utilizing third party one with simplicity and security (@whatisgravity).

I was already contacted by high profile institutional donors awaiting for a minimal structure to donate to the organization driving the development of the whole Ethereum<sup>CLASSIC</sup>'s ecossystem. But we don't want to receive funds without transparency and respect to the community. We don't want to screw up the opportunity we have here neighter.

Receiving funds from institutions has to be done in a professional manner with a legaly stabilished company. I propose the creation of this company that would be a channel for receiving funds.

Allocation of funds are outside of the scope of it because they would actually be allocated the best way possible with community participation in the process with Ethereum<CLASSIC>'s sound values and the engine provide by crowdsourcing solution provider.

**Comment by whatisgravity** [comment]
@GillesChamp I don't know if I understand the question, but I will try to answer what I believe is being asked. If you could clarify your post I can do my best to respond to the other issues raised. 

> Why do you want to reject the idea of a Foundation or a consortium or any sort of no-profit organization ?

 I don't necessarily reject this idea but I do think what we want to accomplish can be accomplished with the tools of the platform without the need the establish a legal organization in the traditional sense. Doing it in the traditional way would incur costs, eliminates pseudoanonymity and in my opinion the worst case scenario concentrates power. 

> There is not so much time and at any moment a small new group can take a prominent position. What if, suppose, 3 new developers should start to work on some new tools right now asking to be crowdfunded as Ethereum Classic Consortium?

They are welcome to do this, I encourage multiple development projects. It would be better if the developers of a cryptocurrency had to negotiate in the way browser developers have to negotiate changes to the HTTP. This method has negative aspects but it also has many benefits, one of the most important being that it is decentralized.

We should not fear competition but encourage it, may the best engineering win.

> They would be able to take some sort of imprimatur while you are wasting your time in long discussions.

When the topic is the best way to secure a community trust, long discussions are needed. Diversity of perspective is essentially directly related to security. We will also need extensive code review. Which is why I agree for simplicity, because getting a simple but secure contract is more important than discussing potentially useful features.

> I suggest you involve in your group a consultant able to drive you in a consortium and once done you will put mind to how to use the collected funds.

What kind of consultant? I would need more specific information to formulate a response to this suggestion.

> In the mean time, add a web page to your site with the donor list and do not forget that the Ethereum Fundation has legal rights on the term "Etehreum" so - probably - any official organization started to manage ETC must avoid the term "ETHEREUM" in the name, that is a real issue.

I'm confused by this suggestion.

I'm psuedoanonymous for a reason, one reason being I don't care about any existing  trademarks or copyright laws regarding Ethereum. The idea for Ethereum was created out of existing ideas within the cypherpunk community and our original chain best matches the description on the ethereum.org website. 
These and other reasons are why we will continue using the name Ethereum in the ways we decide to.

Regardless how you feel about us using the name Ethereum: You and anyone else will be completely unable to stop us from using "Ethereum" on whatever we as a community deem is Ethereum.

You are arguing with a Kopimist about trademark violations.

So there is no issue.

**Comment by whatisgravity** [comment]
@realcodywburns I'm familiar with that contract and I do think it may be a good starting point. We may want to put more restrictions on the output functions. We may also need some simple voting system with the ability to have different thresholds for different types of output functions. For example, it should take less people to vote for a payout to active developers members but more to send held community funds to a new contract.

Your first suggestion though and we may just want to add the voting as a module, but even if we do that we need to expose the map of users in a way it can be tracked by a separate voting contract.

I'm interested in knowing your reaction to this idea.

**Comment by realcodywburns** [comment]
@gilleschamp under the ethereum foundations terms of service, ethereum is a verb similar to google. Our network was actually 'planned' for and identified as a risk under: RISK OF ALTERNATIVE, UNOFFICIAL ETHEREUM NETWORKS. Odd really.

@whatisgravity I think simplicity is the key. More complex can come later.

 I respect your desire for psuedoanonymity. I am fearful of our crypt  anarchial utopia being squandered. This project is truly the wild wired west, where the only guarantee is that without fail (or fork) the system will execute the code. It is only a matter of time before some twitter kid, venture capitalist, or media celebrity 'claims' classic. I think we should plant a flag publicly saying this network is free and will remain that way. And we will fight to keep it that way, its ours now

**Comment by ChuckSRQ** [comment]
I very much like the idea of per project funding. Not only do I think it will help with decentralization of the organization. But I also think it will be a good way to raise funds from donations and the public. 

It can be difficult for people to donate to an organization when they do not see where the money is going. With project based funding, the general public and ETC users will be able to donate to the project of their choosing and in effect be voting for the projects they think would be best. 

For example we could have multiple projects/groups to come up with a hard fork to get rid of the difficulty bomb. One group could be set on staying on PoW, another on PoS. Based on the progress and reports of said groups/projects, the users within the community might vote with their money towards the project they feel is best.

**Comment by whatisgravity** [comment]
@ChuckSRQ Thank you for articulating your opinion on this

> It can be difficult for people to donate to an organization when they do not see where the money is going. 

I firmly believe this too, which is why I don't think we need to actively raise money like a crowd sale. We should focus on development while providing a transparent and decentralized framework to receive donations. 

I actively discourage anyone from donating until they see results, once this organization can prove it has capable members, who are producing positive results for the community then they can decide if they want to contribute with financial donations instead of time. 

> One group could be set on staying on PoW, another on PoS.

This is not something we can easily avoid, but I believe the best way to address the issue is to begin by deciding how we would test the security of a proof-of-stake system. Once we have a better idea of what we are looking for we can test proposed systems using simulations. I have begun some work in this area, I believe it would be better to start this work early. 

As for the defusal, a proposal has already been made and the discussion already started within go-ethereum repository. In it you will find my suggestions regarding this subject and input provided by others.

**Comment by whatisgravity** [comment]
@realcodywburns We plant that flag together, right now, with every moment we invest into this community initiative.

I'm open to hear other ways to do plant that flag in a way that avoids simply making a new iteration of the previous system that failed us.

My hope is our community has been hardened by this event and will be less susceptible to cult of personality social engineering attacks.

**Comment by realcodywburns** [comment]
Getting rich isn't my motivation for my work here. But neither is going poor. We are possibly at a level of piracy never before even thought of. Think "You wouldn't download a car, would you?" Well, we are full tilt into commandeering a billion dollar blockchain network in order to free it for the world. This will require more financial support than any of us can provide alone. There are many allies in the world who are wanting to help, they want use to prove the some people are not motivated by the money and will stand on principle. It would be foolish to ignore them. 3 months from now when etc surpasses eth in market cap because of the ideals it holds, I want to be able to defend it by any means necessary.

**Comment by whatisgravity** [comment]
I think we agree, we need a system to hold development funds and I think starting this process will provide an added level of legitimacy. 

As a result of this conversion, in my opinion, regardless of how we should raise money for development, or even regardless how we propose to distribute it to developers, we need a secure way to handle basic storage in a transparent, secure and decentralized way. 

I do think it needs to be more complex than just the multisig wallet. In my opinion we should focus on that goal, then we can propose modular updates to that and discuss and refine which interact with the neutral base. It also lets us to make progress while allowing us to put off major decisions, which will allow more people to provide their input.

I believe the most pressing issues are then:

1. How do we decide who holds the original multisig keys. 
2. How will the output functions work
3. What is the threshold needed to generate an output (per output type?)
4. Determine if the voting system should be in this contract or decide what API will it need to interface with a voting module.

If you disagree on this path, let me know what issues you see or what alternative you think would be better

**Comment by NDNewell** [comment]
Great ideas raised by all.

@realcodywburns is right in that simplifying this process is very important.

@whatisgravity while I do understand that we need some sort of system for funding etc. I think we can be more effective by providing a place where project ideas are created by individual developers or groups of developers. Participants in the ETC ecosystem can, as @realcodywburns pointed out vote with their money on the project they prefer. The funds could be allocated by participants' money going directly to the group/individual devs, so there is no need for multisig keys or a 'voting system' etc. It's complete decentralization. Let the free market decide and let the best project proposal win or even create alternative options/versions/projects/chains etc.

**Comment by whatisgravity** [comment]
@NDNewell My concern with that system is rooted in two primary issues:

1. It allows for plutocratic/oligarchic systems which are inherently not diverse decide engineering decisions. Handing off engineering decisions to people capable of obtaining large amounts of tokens does not appear to me to properly award ideas purely on their merit
2. This may not be relevant, depending on your proposed design, but if it is held funds directed by token voting it could be gamed and drained by people above a threshold of value.

Can you explain the alternative system you are proposing in more detail? It is hard to discuss it without knowing exactly what options are being discussed.

**Comment by NDNewell** [comment]
Sure. To address your concerns:

1. I'm not sure how centralizing control of funds among a few people holding multisig keys would be less plutocratic/oligarchic. If anything, that seems very open for abuse even with a voting system in place. In my system, anyone can come up with an idea, post it, and based on the merit of the idea, receive funds. The only centralization would be providing a space/page for those who wish to contribute/develop to post their ideas.

2. Also, funds wouldn't be held by anyone, so there is nothing to direct by us or anyone. Instead, projects are funded by simply sending ETC to each project's funding address. We could provide guidelines for devs/groups with ideas can provide transparency, milestones, communcation etc., but ultimately reputation, credibility, and due diligence on the part of people donating is key to avoid gaming/scams.

It's simply just taking the crowdfunding concept and applying it to internal development/projects. What do you think?

**Comment by realcodywburns** [comment]
Im not sure how point two is different from the multisig we have been discussing. I am not opposed to many dev funds (think venture capital) operating in the classic chain space at some point. The topic at hand is our fund and what happens after someone drops a coin in the cup.

**Comment by ProphetDaniel** [comment]
Created Ethereum<sup>CLASSIC</sup> consider.it [site](etc.consider.it). Then created [poll ](https://etc.consider.it/should-ethereum-classic-create-a-company-for-collecting-institutional-investments?results=true)to address the creation of the company as a live example.

**Comment by realcodywburns** [comment]
Company is the wrong word. 

I'd be interested in a nonprofit foundation to support development and provide defense. In the charter it could be stated that the np would remain apathetic in all matters of governance and exists solely for the public benefit.    

The np could host a crowd funding website where anyone could post project ideas, and investors could choose who they like or 'helicopter drop' funds to the foundation who would distribute the funds equally.

**Comment by NDNewell** [comment]
@realcodywburns I guess what I'm trying to get at is there isn't one 'cup', but rather multiple  dev groups' 'cups'. We just provide the table for devs to place their 'cups'. Then we don't need to worry about what happens after someone drops a coin as each group is automatically funded by whichever coins come their way.

Why have a foundation at all? Why not just 'helicopter drop' directly to the dev team with the idea?

**Comment by whatisgravity** [comment]
NDNewell: I can see the benefits of both designs and do think in general we should push for multiple groups, possibly even operating in entirely different ways that negotiate with each other. 

I think it boils down how much control should the developers themselves have over the distribution. And I honestly can see benefits and problems with both situations. So I'm interested hearing more perspectives.

The reason I lean towards making this specific system created in a way developers allocate funds is because it allows for the possibility to operate as a small technocracy. 

It makes it so that priorities the developers feel are important are funded even if they don't appear to be important in the short term. I think the alternative system may primarily operate within the short term. It also lowers the number of people to convince lower making quick changes still feasible. 

If this organization made bad decisions, over time I would assume people would stop donating and put their contributions elsewhere.

Stating that I do recognize the nature of the specific system is not completely decentralized. However I think for this system the trade offs may be wroth it. We may be able to make it more decentralized by having elected key holders decided by active developers. 

I don't see why an organization with per organization funding and projects with per project funding could not live in the same ecosystem, even share resources. 

I think the focus should be determining what minimum we can agree on, because we may be able to create a basic contract foundation with satisfies both designs.

**Comment by whatisgravity** [comment]
Closing this to funnel discussion into a single thread, my general conclusion is we should aim for building tools for both to help support the overall developer community.
