### ISSUE TITLE
Projects and idea presenting for viewers

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumproject/project-funding#6]
According to the awesome idea given by @avtarsehra [here](https://github.com/ethereumproject/project-funding/issues/3):

> Has anyone considered forking the Open Bazzar (OB) project to utilise as a decentralised mechanism for posting and funding projects? I am not familiar with the finer details of OB, but I think it would be fairly straight forward to adapt to project funding, and the moderated payment process can be leveraged to collate funds until a threshold is reached or a time expiry is reached. Unlike in the Bitcoin OB this ETC funding marketplace moderated process can be a very basic smart contract, but it could have some form of multisig release to avoid funds getting stuck. This is only an idea. As I mention I am not that familiar with the OB project, and there may be complexities which mean this would be challenging. Or it could be layer that is added at a later date... Thoughts?

In my opinion It's not that hard to execute the customization, if there's nobody able to take the lead here I'll try pushing my development schedule a little tighter to make it happen once community aggrees upon it.

I opened a [poll](https://etc.consider.it/fork-open-bazaar-for-presenting-projectsideas-to-ethereum-classic-viewers?results=true) for voting this development.

**Comment by matthewjamesr** [comment]
I do not like this idea only for one reason. As OpenBazaar is currently coded, the person posting their content must leave their client online at all time. As soon as they shut down that users posted content is no longer accessible. Once their client is back online, it is then, again accessible.

What about deploying a new, customized blockchain using Multichain? I have toyed around with it before and not too difficult. I even wrote a block explorer on top of my custom chain.

**Comment by matthewjamesr** [comment]
Addon: we can create a blockchain with a zero transaction fee and no mining rewards. Any one running the daemon will help strengthen the network. We can just write a custom simple meteor-based wallet on top of it and have it scan the blockchain for OP_RETURN code relevant to store a new proposal.

**Comment by whatisgravity** [comment]
I agree with the self hosting requirement of OB being a major drawback. They may have been better off using a second DHT. 

I think this adds a lot of complexity to the design, while it may be a good way to present proposals it may be just as easy to build a web UI for data stored in a smart contract.

**Comment by avtarsehra** [comment]
What if the content can be stored on IPFS in a standard structured format?

**Comment by matthewjamesr** [comment]
Why not just send the proposals via a contract then, and sign yes or no with our publically posted PGP keys on a webapp? I can make said-app easily. Will just need to figure out how to scan the blockchain for proposals and log them to the apps db.

**Comment by avtarsehra** [comment]
@Matthewjamesr that's a good idea. Actually we already have a platform to do this, all we would need to do is move the project db to a etc smart contract for data storage. But then we still come back to the challenge. This would mean there is less reliance on the centralised platform and anyone can deploy competing platforms to tap into the same data and execute transactions. It's a very good idea, and just utilises etc.

**Comment by avtarsehra** [comment]
*I meant in previous comment - challenge of centralisation. But that's not issue as indicated by following remark i.e. Anyone can deploy a platform to tap into the data.

**Comment by avtarsehra** [comment]
I've been testing the OB platform and can see what @matthewjamesr was talking about. I believe the developers of OB went down that route as they didn't have access to smart contract functionality. I think ETC has a huge advantage here, that we can utilise the ETC chain to store all data, and even if we fork the OB application, projects could always remain visible even if a user closes their client. The only challenge would be that the images wouldn't be there - but this is not much of an issue. The more I think about this the more I feel that we can build a very low complexity solution on ETC with basic contracts for basic user data (basic user details, historic ratings etc), funding project data and simple fund escrowing, and then the more complex logic can be on the web app presentation layers, which can be created by any dev. We could even end up with multiple platforms - similar to multiple torrent sites that provide links to files on a P2P network. Success of any one platform would then only be related to extra features, reliability and fairness they provide to end users. I feel this is probably the closes we will get to a truly decentralised marketplace model that minimizes smart contract complexity.

**Comment by whatisgravity** [comment]
I assume the OB proposal is tabled in favor of at least consider.it? If so @ProphetDaniel can you close the thread so we can funnel discussion.
